package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"

	"github.com/luis13005/cleanarchitecture/internal/infra/graph/model"
	"github.com/luis13005/cleanarchitecture/internal/usecase"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input *model.OrderInput) (*model.Order, error) {
	dto := usecase.OrderInputDTO{
		ID:    input.ID,
		Price: input.Price,
		Tax:   input.Tax,
	}

	outputDTO, err := r.CreateOrderUseCase.Execute(dto)
	if err != nil {
		return nil, err
	}

	order := &model.Order{
		ID:         outputDTO.ID,
		Price:      outputDTO.Price,
		Tax:        outputDTO.Tax,
		FinalPrice: outputDTO.FinalPrice,
	}

	return order, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
